#Requires -Version 5.1
<#
.SYNOPSIS
    VM topology definitions and IP pre-flight checks for the AD training lab.

.DESCRIPTION
    Single source of truth for the AD training lab's topology, generalized
    from /office-hours and /plan-eng-review's original fixed 5-VM design to a
    configurable VM count per role (the trainer chooses how many servers and
    clients to deploy, see Get-LabVmDefinitions' Count parameters):
      - Domain A (CORP): DC1, DC2, ... - redundancy/replication/FSMO practice
        across as many DCs as requested.
      - Domain B (PARTNER): PDC1, PDC2, ... - a separate forest for trust-
        relationship practice with Domain A. Set the count to 0 to skip this
        domain entirely (no trust-practice VMs built).
      - CL1, CL2, ... - clients joined to Domain A.
    Hostnames are generated by role+index; IP addresses auto-increment from a
    single base address in that same order (Domain A, then Domain B, then
    clients) so the trainer only has to pick a starting address, not type one
    per VM. Use NameOverrides to rename any generated VM afterward - safe to
    do freely, since no AD DS role is installed by this script.
#>

Set-StrictMode -Version Latest

# Network block is a PLACEHOLDER until the BLOCKING LAN open question (design doc
# line 64) is resolved with a network admin: a reserved static IP range OUTSIDE the
# real LAN's DHCP scope. Override via -NetworkConfig on Get-LabVmDefinitions once
# the real block is confirmed - do not deploy against these placeholder values.
$Script:DefaultNetworkConfig = [PSCustomObject]@{
    SubnetPrefixLength = 24
    Gateway            = '192.168.1.1'
    DnsServers         = @('192.168.1.1')
    # First of a consecutive block reserved for this lab, outside the LAN's
    # DHCP scope - one address per VM, allocated in generation order (Domain
    # A DCs, then Domain B DCs, then clients).
    BaseIPAddress      = '192.168.1.241'
}

function Get-LabVmDefinitions {
    <#
    .SYNOPSIS
        Builds the lab topology as an array of definition objects, sized by
        the Count parameters below.
    .PARAMETER DomainAServerCount
        Number of DCs in Domain A (corp.lab) - DC1, DC2, .... The first one
        created (DC1) creates the forest; the rest are additional DCs for
        redundancy/replication/FSMO practice. Minimum 1 - Domain A always
        exists.
    .PARAMETER DomainBServerCount
        Number of DCs in Domain B (partner.lab) - PDC1, PDC2, .... A separate
        forest for trust-relationship practice with Domain A. Set to 0 to
        skip Domain B entirely (no trust-practice VMs built).
    .PARAMETER ClientCount
        Number of clients joined to Domain A - CL1, CL2, ....
    .PARAMETER NetworkConfig
        Override the placeholder network block once the real reserved range is
        confirmed with the network admin (design doc's BLOCKING open question).
        BaseIPAddress is the first of a consecutive block; one address gets
        allocated per VM in generation order (Domain A, then B, then clients).
    .PARAMETER NameOverrides
        Optional hashtable keyed by the canonical generated name (DC1, DC2,
        ..., PDC1, ..., CL1, ...) renaming that VM's actual hostname. Safe to
        rename freely - no AD DS role gets installed by this script, so
        there's no domain/FSMO coupling to the canonical names beyond this
        function's own internal lookup (Domain/NetBiosName/OSImage/IP slot
        stay keyed by the canonical name regardless of what the VM ends up
        actually called).
    .PARAMETER IPOverrides
        Optional hashtable keyed by the canonical generated name, overriding
        that VM's auto-allocated IP address with an arbitrary one. Use this
        when the sequential allocation from BaseIPAddress doesn't fit (e.g.
        a gap already in use) - every other VM still gets its normal
        sequential address; only the overridden ones change.
    #>
    [CmdletBinding()]
    param(
        [ValidateRange(1, 99)]
        [int]$DomainAServerCount = 2,
        [ValidateRange(0, 99)]
        [int]$DomainBServerCount = 1,
        [ValidateRange(0, 99)]
        [int]$ClientCount = 2,
        [PSCustomObject]$NetworkConfig = $Script:DefaultNetworkConfig,
        [hashtable]$NameOverrides = @{},
        [hashtable]$IPOverrides = @{}
    )

    $totalCount = $DomainAServerCount + $DomainBServerCount + $ClientCount
    $baseOctets = $NetworkConfig.BaseIPAddress -split '\.'
    $lastOctetStart = [int]$baseOctets[3]
    if (($lastOctetStart + $totalCount - 1) -gt 255) {
        throw "Get-LabVmDefinitions: $totalCount VMs starting at $($NetworkConfig.BaseIPAddress) would run past .255 - pick a lower BaseIPAddress, or reduce the VM count."
    }
    $ipPrefix = $baseOctets[0..2] -join '.'

    # Each tuple is (name prefix, role, domain, netbios name, OS image, count).
    # Built as a flat list of role-groups rather than a nested helper function
    # that mutates a shared counter - PowerShell's scoping makes a nested
    # function modifying its caller's loop variable awkward ($script: would
    # leak the counter across separate calls to this function within the same
    # module session, since this module's $script: scope persists for the
    # whole session, not just one call).
    $roleGroups = @(
        @{ Prefix = 'DC'; Count = $DomainAServerCount; Role = 'DomainController'; Domain = 'corp.lab'; NetBiosName = 'CORP'; OSImage = 'Server2022' }
        # PDC-prefixed (not DC3, DC4, ...) to stay visually distinct from
        # Domain A's own DCs regardless of either count.
        @{ Prefix = 'PDC'; Count = $DomainBServerCount; Role = 'DomainController'; Domain = 'partner.lab'; NetBiosName = 'PARTNER'; OSImage = 'Server2022' }
        # Client10 template's checkpoint merge hangs reproducibly on this
        # host (see TODOS.md) - all clients use Client11 until that's
        # resolved. Was: mixed-fleet practice (some Win10, some Win11).
        @{ Prefix = 'CL'; Count = $ClientCount; Role = 'Client'; Domain = 'corp.lab'; NetBiosName = 'CORP'; OSImage = 'Client11' }
    )

    $definitions = [System.Collections.Generic.List[PSCustomObject]]::new()
    $nextOctet = $lastOctetStart

    foreach ($group in $roleGroups) {
        for ($i = 1; $i -le $group.Count; $i++) {
            $definitions.Add([PSCustomObject]@{
                Name         = "$($group.Prefix)$i"
                Role         = $group.Role
                Domain       = $group.Domain
                NetBiosName  = $group.NetBiosName
                IsFirstDC    = ($i -eq 1 -and $group.Role -eq 'DomainController')  # creates that domain's forest
                OSImage      = $group.OSImage
                IPAddress    = "$ipPrefix.$nextOctet"
                PrefixLength = $NetworkConfig.SubnetPrefixLength
                Gateway      = $NetworkConfig.Gateway
                DnsServers   = $NetworkConfig.DnsServers
            }) | Out-Null
            $nextOctet++
        }
    }

    foreach ($vmDef in $definitions) {
        # Both overrides key off the canonical generated name - captured
        # BEFORE the rename below, so IPOverrides and NameOverrides resolve
        # independently regardless of which one (if either) is supplied.
        $canonicalName = $vmDef.Name
        if ($IPOverrides.ContainsKey($canonicalName)) {
            $vmDef.IPAddress = $IPOverrides[$canonicalName]
        }
        if ($NameOverrides.ContainsKey($canonicalName)) {
            $vmDef.Name = $NameOverrides[$canonicalName]
        }
    }

    return $definitions.ToArray()
}

function Test-IPAvailable {
    <#
    .SYNOPSIS
        Pre-flight check (Code Quality Issue 4): is this IP already in use on the LAN?
    .DESCRIPTION
        Pings the address once. A response means something else already holds it -
        deploying a VM with this static IP would create a silent ARP conflict
        instead of a clear error. Returns $true when the address is free.
    .OUTPUTS
        [bool] $true if the IP did NOT respond (free), $false if it DID respond (taken).
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [string]$IPAddress
    )

    try {
        # -ComputerName, not -TargetName: the lab hosts run Windows PowerShell
        # 5.1, where Test-Connection doesn't have -TargetName/-TimeoutSeconds
        # (those are PowerShell 7+ additions). Confirmed by actually running
        # this against a real Windows 10/Server host during testing.
        $reply = Test-Connection -ComputerName $IPAddress -Count 1 -ErrorAction SilentlyContinue -Quiet
        return -not $reply
    }
    catch {
        # Test-Connection itself failing (e.g. no ICMP permission) is not the same
        # as "IP is free" - surface it rather than assuming success.
        throw "Test-IPAvailable: could not determine availability of $IPAddress - $($_.Exception.Message)"
    }
}

function Test-LabIPBlockAvailable {
    <#
    .SYNOPSIS
        Runs Test-IPAvailable across every VM definition before any VM is touched.
    .DESCRIPTION
        Deploy.ps1 calls this BEFORE creating any differencing disk or VM, so a
        conflict aborts the whole run up front (Code Quality Issue 4) rather than
        surfacing mid-loop after some VMs already exist.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [PSCustomObject[]]$VmDefinitions
    )

    $conflicts = @()
    foreach ($vm in $VmDefinitions) {
        if (-not (Test-IPAvailable -IPAddress $vm.IPAddress)) {
            $conflicts += "$($vm.Name) -> $($vm.IPAddress)"
        }
    }

    if ($conflicts.Count -gt 0) {
        throw "Pre-flight IP check failed - already in use on the LAN: $($conflicts -join ', '). Reserve a different block or resolve the conflicting device before deploying."
    }
}

Export-ModuleMember -Function Get-LabVmDefinitions, Test-IPAvailable, Test-LabIPBlockAvailable
